<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Projeto Vitalidade Total - Nutrimos os corpos e nutrimos a mente.">
    <title>Projeto Vitalidade Total 💚</title>
    <link rel="stylesheet" href="styles.css"> <!-- Link para o CSS externo -->
</head>
<body>
    <!-- Cabeçalho com logo e menu de navegação -->
    <header>
        <div class="logo">
            <h1>Projeto Vitalidade Total 💚</h1>
        </div>
        <nav>
            <ul>
                <li><a href="#inicio">Início</a></li>
                <li><a href="#alimentacao">Alimentação</a></li>
                <li><a href="#receitas">Receitas</a></li>
                <li><a href="#exercicios">Exercícios</a></li>
                <li><a href="#alongamentos">Alongamentos</a></li>
                <li><a href="#yoga">Yoga e Meditação</a></li>
                <li><a href="#dicas">Dicas de Bem-Estar</a></li>
                <li><a href="#contato">Contato</a></li>
                <li><a href="#blog">Blog</a></li>
            </ul>
        </nav>
    </header>

    <!-- Seção de introdução com banner e call-to-action -->
    <section id="inicio" class="intro">
        <div class="banner">
            <h2>Nutrimos os corpos e nutrimos a mente</h2>
            <p>Viva com mais energia e equilíbrio! Explore dicas de alimentação, exercícios, e muito mais para viver uma vida saudável.</p>
            <a href="#alimentacao" class="cta-button">Comece agora sua jornada de bem-estar!</a>
        </div>
    </section>

    <!-- Seção de Alimentação Saudável -->
    <section id="alimentacao">
        <h2>Alimentação Saudável</h2>
        <p>Acompanhe um cronograma alimentar balanceado para garantir que seu corpo receba todos os nutrientes essenciais.</p>
        <div class="cronograma">
            <h3>Cronograma Alimentar Semanal</h3>
            <ul>
                <li><strong>Semana 1:</strong> Dieta Balanceada – Inclui café da manhã, almoço, jantar e lanches equilibrados.</li>
                <li><strong>Semana 2:</strong> Dieta Mediterrânea – Rica em frutas, legumes, peixes e azeite de oliva.</li>
                <li><strong>Semana 3:</strong> Dieta Detox – Enfoque em sucos verdes, sopas leves e alimentos que limpam o corpo.</li>
            </ul>
            <a href="#receitas" class="cta-button">Veja as receitas</a>
        </div>
    </section>

    <!-- Seção de Receitas Saudáveis -->
    <section id="receitas">
        <h2>Receitas Saudáveis</h2>
        <p>Receitas rápidas e deliciosas, cheias de nutrientes essenciais.</p>
        <div class="receita">
            <h3>Sopa Detox de Abóbora e Gengibre</h3>
            <p>Ingredientes: Abóbora, gengibre, azeite, alho, cebola, sal...</p>
            <p>Modo de preparo: Refogue o alho e a cebola, adicione a abóbora e o gengibre, cozinhe até ficar macio...</p>
            <a href="#" class="cta-button">Compartilhar</a>
        </div>

        <div class="receita">
            <h3>Salada de Quinoa com Abacate</h3>
            <p>Ingredientes: Quinoa, abacate, tomate, limão, azeite, sal...</p>
            <p>Modo de preparo: Cozinhe a quinoa e misture com os outros ingredientes...</p>
            <a href="#" class="cta-button">Imprimir receita</a>
        </div>
    </section>

    <!-- Seção de Exercícios Físicos -->
    <section id="exercicios">
        <h2>Exercícios Físicos</h2>
        <p>Rotina de exercícios para melhorar força e resistência, adequada para iniciantes e intermediários.</p>
        <div class="cronograma-exercicios">
            <h3>Cronograma de Treinos</h3>
            <ul>
                <li><strong>Segunda-feira:</strong> Caminhada rápida (30 min)</li>
                <li><strong>Terça-feira:</strong> Circuito funcional (45 min)</li>
                <li><strong>Quarta-feira:</strong> Bicicleta ao ar livre (60 min)</li>
                <li><strong>Quinta-feira:</strong> Treino de força (30 min)</li>
                <li><strong>Sexta-feira:</strong> Sessão de Yoga (45 min)</li>
            </ul>
            <a href="#" class="cta-button">Baixe o cronograma completo</a>
        </div>
    </section>

    <!-- Seção de Alongamentos Diários -->
    <section id="alongamentos">
        <h2>Alongamentos Diários</h2>
        <p>Práticas de alongamento essenciais para evitar lesões e melhorar a flexibilidade.</p>
        <div class="exercicio-alongamento">
            <h3>Alongamento de Braços</h3>
            <p>Levante os braços acima da cabeça, mantendo-os esticados. Segure por 20 segundos.</p>
            <img src="img/alongamento-bracos.jpg" alt="Alongamento de Braços">
        </div>
        <div class="exercicio-alongamento">
            <h3>Alongamento de Pernas</h3>
            <p>Sentado, estenda as pernas e tente alcançar os pés com as mãos. Mantenha por 20 segundos.</p>
            <img src="img/alongamento-pernas.jpg" alt="Alongamento de Pernas">
        </div>
    </section>

    <!-- Seção de Yoga e Meditação -->
    <section id="yoga">
        <h2>Yoga e Meditação</h2>
        <p>Relaxe corpo e mente com nossas aulas de yoga e sessões de meditação guiadas.</p>
        <div class="aula-yoga">
            <h3>Posição da Montanha</h3>
            <p>Fique em pé, pés juntos, braços ao lado do corpo. Respire profundamente.</p>
            <video src="videos/posicao-montanha.mp4" controls></video>
        </div>
        <div class="aula-yoga">
            <h3>Cachorro Olhando para Baixo</h3>
            <p>Apoie as mãos e os pés no chão, formando um V invertido com o corpo. Respire lentamente.</p>
            <video src="videos/cachorro-baixo.mp4" controls></video>
        </div>
        <a href="#" class="cta-button">Baixe o Guia Completo de Yoga</a>
    </section>

    <!-- Seção de Dicas de Bem-Estar -->
    <section id="dicas">
        <h2>Dicas de Bem-Estar</h2>
        <p>Sugestões para manter o equilíbrio e bem-estar no dia a dia.</p>
        <ul>
            <li><strong>Hidrate-se:</strong> Beba ao menos 2 litros de água diariamente.</li>
            <li><strong>Alimente-se bem:</strong> Prefira alimentos frescos e evite processados.</li>
            <li><strong>Durma bem:</strong> Mantenha uma rotina de sono de 7 a 8 horas.</li>
        </ul>
    </section>

    <!-- Seção do Blog -->
    <section id="blog">
        <h2>Blog</h2>
        <p>Últimos artigos sobre saúde, alimentação e bem-estar.</p>
        <article>
            <h3>Benefícios da Dieta Mediterrânea</h3>
            <p>A dieta mediterrânea é conhecida por melhorar a saúde cardíaca e promover longevidade...</p>
            <a href="#">Leia mais</a>
        </article>
        <article>
            <h3>Como Meditar em 5 Minutos</h3>
            <p>Aprenda técnicas simples para meditar e relaxar em poucos minutos por dia...</p>
            <a href="#">Leia mais</a>
        </article>
    </section>

    <!-- Seção de Contato -->
    <section id="contato">
        <h2>Contato</h2>
        <p>Fale conosco para tirar dúvidas ou compartilhar sugestões.</p>
        <form action="enviar-formulario.php" method="post">
            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="mensagem">Mensagem:</label>
            <textarea id="mensagem" name="mensagem" rows="4" required></textarea>

            <button type="submit" class="cta-button">Enviar</button>
        </form>
    </section>

    <!-- Rodapé com links sociais -->
    <footer>
        <p>© 2024 Projeto Vitalidade Total 💚 - Todos os direitos reservados.</p>
        <div class="social-icons">
            <a href="#"><img src="img/facebook-icon.png" alt="Facebook"></a>
            <a href="#"><img src="img/instagram-icon.png" alt="Instagram"></a>
            <a href="#"><img src="img/twitter-icon.png" alt="Twitter"></a>
        </div>
    </footer>

</body>
</html>
